In [1]:
import numpy as np
import json
import pandas as pd

In [2]:
import napari
viewer = napari.Viewer()

/Users/segonzal/opt/anaconda3/envs/starfish_napari/lib/python3.7/site-packages/napari/_qt/qt_viewer.py:344: UserWarning: Attempting to unbind an action which does not exists (napari:also_select_layer_above), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.
  action_manager.unbind_shortcut(action)
/Users/segonzal/opt/anaconda3/envs/starfish_napari/lib/python3.7/site-packages/napari/_qt/qt_viewer.py:344: UserWarning: Attempting to unbind an action which does not exists (napari:also_select_layer_below), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.
  action_manager.unbind_shortcut(action)
/Users/segonzal/opt/anaconda3/envs/starfish_napari/lib/python3.7/site-packages/napari/_qt/qt_viewer.py:344: UserWarning: Attempting to unbind an

## Load cell-type map 

In [4]:
df = pd.read_csv('../../segmentation_cell_stats.csv')

In [5]:
df.head()

cell             x             y  cluster  n_transcripts  \
0  CR2536e37ea-1  10018.545455  10127.090909        2             11   
1  CR2536e37ea-2  10059.478261  10066.521739        2             23   
2  CR2536e37ea-3  10103.750000  10022.833333        2             12   
3  CR2536e37ea-4  10190.555556  10033.777778        2              9   
4  CR2536e37ea-5  10146.227273  10202.636364        2             22   

    density  elongation    area  avg_confidence  avg_assignment_confidence  \
0  0.007931       8.198  1387.0          0.9985                     0.9418   
1  0.007206       1.791  3192.0          0.9999                     0.9157   
2  0.008753       5.660  1371.0          0.9987                     0.9550   
3  0.012470       1.466   721.5          0.9998                     0.9956   
4  0.009228       3.790  2384.0          0.9998                     0.9600   

   max_cluster_frac  lifespan  
0          0.727273        50  
1          0.956522        50  
2          1.000000        50  
3          0.777778        50  
4          1.000000        50

In [32]:
dots = np.concatenate((rep(df.x), rep(df.y)), axis=1)

In [36]:
color_map = {1: 'red', 2: 'blue', 3: 'green', 4: 'pink'}

In [37]:
color_array = [color_map[i] for i in df.cluster.loc[:]]

In [38]:
color_array

['blue',
 'blue',
 'blue',
 'blue',
 'blue',
 'blue',
 'blue',
 'green',
 'blue',
 'blue',
 'blue',
 'pink',
 'blue',
 'blue',
 'red',
 'blue',
 'blue',
 'red',
 'blue',
 'red',
 'red',
 'red',
 'red',
 'blue',
 'blue',
 'blue',
 'red',
 'red',
 'blue',
 'blue',
 'red',
 'blue',
 'blue',
 'green',
 'red',
 'green',
 'red',
 'red',
 'blue',
 'blue',
 'green',
 'blue',
 'red',
 'blue',
 'blue',
 'red',
 'blue',
 'red',
 'red',
 'red',
 'blue',
 'red',
 'blue',
 'red',
 'red',
 'blue',
 'red',
 'red',
 'red',
 'blue',
 'red',
 'green',
 'green',
 'blue',
 'red',
 'red',
 'blue',
 'red',
 'blue',
 'blue',
 'red',
 'red',
 'blue',
 'red',
 'green',
 'red',
 'blue',
 'red',
 'blue',
 'red',
 'green',
 'blue',
 'green',
 'red',
 'blue',
 'red',
 'blue',
 'red',
 'red',
 'blue',
 'green',
 'blue',
 'blue',
 'blue',
 'blue',
 'red',
 'blue',
 'red',
 'blue',
 'red',
 'red',
 'red',
 'red',
 'red',
 'red',
 'red',
 'green',
 'red',
 'red',
 'blue',
 'red',
 'red',
 'red',
 'green',
 'red',
 'blu

In [39]:
viewer.add_points(dots, size = 20, face_color=color_array)

<Points layer 'dots [2]' at 0x7ff73bbd3d50>

In [7]:
help(viewer.add_points)

Help on method add_points:

add_points(data=None, *, ndim=None, features=None, properties=None, text=None, symbol='o', size=10, edge_width=1, edge_color='black', edge_color_cycle=None, edge_colormap='viridis', edge_contrast_limits=None, face_color='white', face_color_cycle=None, face_colormap='viridis', face_contrast_limits=None, out_of_slice_display=False, n_dimensional=None, name=None, metadata=None, scale=None, translate=None, rotate=None, shear=None, affine=None, opacity=1, blending='translucent', visible=True, cache=True, property_choices=None, experimental_clipping_planes=None, shading='none', experimental_canvas_size_limits=(0, 10000), shown=True) -> napari.layers.points.points.Points method of napari.viewer.Viewer instance
    Add a Points layer to the layer list. 
    
    Parameters
    ----------
    data : array (N, D)
        Coordinates for N points in D dimensions.
    ndim : int
        Number of dimensions for shapes. When data is not None, ndim must be D.
        An e

In [ ]:
napari.add_points

In [19]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

In [24]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [29]:
def rep(data_series):
    return np.reshape(np.array(data_series), (len(data_series), 1))

In [31]:
np.concatenate((rep(df.x), rep(df.y)), axis=1)

array([[10018.54545455, 10127.09090909],
       [10059.47826087, 10066.52173913],
       [10103.75      , 10022.83333333],
       ...,
       [11696.125     , 12307.375     ],
       [11018.        , 14830.        ],
       [13513.66666667, 12328.        ]])

In [ ]:
np.concatenate(df.x)

In [3]:
with open('../segmentation_polygons.json', 'r') as fh:
    data = json.load(fh)

In [5]:
data

{'geometries': [{'coordinates': [[[17821.0, 36211.0],
     [17835.0, 36224.0],
     [17848.0, 36221.0],
     [17849.0, 36216.0],
     [17844.0, 36205.0],
     [17844.0, 36194.0],
     [17850.0, 36192.0],
     [17855.0, 36192.0],
     [17859.0, 36186.0],
     [17856.0, 36183.0],
     [17834.0, 36191.0],
     [17811.0, 36191.0],
     [17821.0, 36211.0]]],
   'type': 'Polygon',
   'cell': 29965},
  {'coordinates': [[[28639.0, 11545.0],
     [28627.0, 11535.0],
     [28622.0, 11525.0],
     [28609.0, 11535.0],
     [28606.0, 11543.0],
     [28626.0, 11554.0],
     [28639.0, 11545.0]]],
   'type': 'Polygon',
   'cell': 45120},
  {'coordinates': [[[17164.0, 34685.0],
     [17173.0, 34705.0],
     [17178.0, 34700.0],
     [17185.0, 34688.0],
     [17184.0, 34671.0],
     [17168.0, 34654.0],
     [17162.0, 34654.0],
     [17149.0, 34654.0],
     [17146.0, 34664.0],
     [17146.0, 34671.0],
     [17164.0, 34685.0]]],
   'type': 'Polygon',
   'cell': 30270},
  {'coordinates': [[[7191.0, 19894.0]

In [28]:
data['geometries'][0]

{'coordinates': [[[17821.0, 36211.0],
   [17835.0, 36224.0],
   [17848.0, 36221.0],
   [17849.0, 36216.0],
   [17844.0, 36205.0],
   [17844.0, 36194.0],
   [17850.0, 36192.0],
   [17855.0, 36192.0],
   [17859.0, 36186.0],
   [17856.0, 36183.0],
   [17834.0, 36191.0],
   [17811.0, 36191.0],
   [17821.0, 36211.0]]],
 'type': 'Polygon',
 'cell': 29965}

In [30]:
data['geometries'][1]

{'coordinates': [[[28639.0, 11545.0],
   [28627.0, 11535.0],
   [28622.0, 11525.0],
   [28609.0, 11535.0],
   [28606.0, 11543.0],
   [28626.0, 11554.0],
   [28639.0, 11545.0]]],
 'type': 'Polygon',
 'cell': 45120}

In [32]:
data['geometries'][0]['coordinates'][0]

[[17821.0, 36211.0],
 [17835.0, 36224.0],
 [17848.0, 36221.0],
 [17849.0, 36216.0],
 [17844.0, 36205.0],
 [17844.0, 36194.0],
 [17850.0, 36192.0],
 [17855.0, 36192.0],
 [17859.0, 36186.0],
 [17856.0, 36183.0],
 [17834.0, 36191.0],
 [17811.0, 36191.0],
 [17821.0, 36211.0]]

In [4]:
cells = []
for i, cell in enumerate(data['geometries'][:]):
    cells.append(np.array(cell['coordinates'][0]))

In [5]:
len(cells)

60052

In [5]:
cells

[array([[17821., 36211.],
        [17835., 36224.],
        [17848., 36221.],
        [17849., 36216.],
        [17844., 36205.],
        [17844., 36194.],
        [17850., 36192.],
        [17855., 36192.],
        [17859., 36186.],
        [17856., 36183.],
        [17834., 36191.],
        [17811., 36191.],
        [17821., 36211.]]),
 array([[28639., 11545.],
        [28627., 11535.],
        [28622., 11525.],
        [28609., 11535.],
        [28606., 11543.],
        [28626., 11554.],
        [28639., 11545.]]),
 array([[17164., 34685.],
        [17173., 34705.],
        [17178., 34700.],
        [17185., 34688.],
        [17184., 34671.],
        [17168., 34654.],
        [17162., 34654.],
        [17149., 34654.],
        [17146., 34664.],
        [17146., 34671.],
        [17164., 34685.]]),
 array([[ 7191., 19894.],
        [ 7183., 19902.],
        [ 7210., 19909.],
        [ 7222., 19918.],
        [ 7221., 19903.],
        [ 7219., 19894.],
        [ 7221., 19877.],
      

In [10]:
np.min(cells[1][:, 0])

28606.0

In [11]:
def fov_region(cells: list, xmin, xmax, ymin, ymax):
    #x_tuple = (xmin, )
    fov_cells = []
    for cell in cells:
        cell_xmin, cell_xmax = np.min(cell[:, 0]), np.max(cell[:, 0])
        cell_ymin, cell_ymax = np.min(cell[:, 1]), np.max(cell[:, 1])
        if (cell_xmin > xmin) & (cell_xmax < xmax):
            fov_cells.append(cell)
    return fov_cells

In [6]:
viewer.add_shapes([cells[0]], shape_type='polygon')

<Shapes layer 'Shapes' at 0x7f9fefff4510>