In [11]:
import numpy as np
import json
import pandas as pd

In [12]:
DATA = '/Users/segonzal/Documents/Repositories/baysor-nextflow-module/segmentation_polygons.json'

In [13]:
import napari
viewer = napari.Viewer()

/Users/segonzal/opt/anaconda3/envs/napari_env/lib/python3.8/site-packages/napari/_qt/qt_viewer.py:395: UserWarning: Attempting to unbind an action which does not exists (napari:also_select_layer_above), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.
  action_manager.unbind_shortcut(action)
/Users/segonzal/opt/anaconda3/envs/napari_env/lib/python3.8/site-packages/napari/_qt/qt_viewer.py:395: UserWarning: Attempting to unbind an action which does not exists (napari:also_select_layer_below), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.
  action_manager.unbind_shortcut(action)
/Users/segonzal/opt/anaconda3/envs/napari_env/lib/python3.8/site-packages/napari/_qt/qt_viewer.py:395: UserWarning: Attempting to unbind an action which d

## Load cell-type map 

In [4]:
df = pd.read_csv('../../segmentation_cell_stats.csv')

In [5]:
df.head()

cell             x             y  cluster  n_transcripts  \
0  CR2536e37ea-1  10018.545455  10127.090909        2             11   
1  CR2536e37ea-2  10059.478261  10066.521739        2             23   
2  CR2536e37ea-3  10103.750000  10022.833333        2             12   
3  CR2536e37ea-4  10190.555556  10033.777778        2              9   
4  CR2536e37ea-5  10146.227273  10202.636364        2             22   

    density  elongation    area  avg_confidence  avg_assignment_confidence  \
0  0.007931       8.198  1387.0          0.9985                     0.9418   
1  0.007206       1.791  3192.0          0.9999                     0.9157   
2  0.008753       5.660  1371.0          0.9987                     0.9550   
3  0.012470       1.466   721.5          0.9998                     0.9956   
4  0.009228       3.790  2384.0          0.9998                     0.9600   

   max_cluster_frac  lifespan  
0          0.727273        50  
1          0.956522        50  
2          1.000000        50  
3          0.777778        50  
4          1.000000        50

In [32]:
dots = np.concatenate((rep(df.x), rep(df.y)), axis=1)

In [36]:
color_map = {1: 'red', 2: 'blue', 3: 'green', 4: 'pink'}

In [37]:
color_array = [color_map[i] for i in df.cluster.loc[:]]

In [38]:
color_array

['blue',
 'blue',
 'blue',
 'blue',
 'blue',
 'blue',
 'blue',
 'green',
 'blue',
 'blue',
 'blue',
 'pink',
 'blue',
 'blue',
 'red',
 'blue',
 'blue',
 'red',
 'blue',
 'red',
 'red',
 'red',
 'red',
 'blue',
 'blue',
 'blue',
 'red',
 'red',
 'blue',
 'blue',
 'red',
 'blue',
 'blue',
 'green',
 'red',
 'green',
 'red',
 'red',
 'blue',
 'blue',
 'green',
 'blue',
 'red',
 'blue',
 'blue',
 'red',
 'blue',
 'red',
 'red',
 'red',
 'blue',
 'red',
 'blue',
 'red',
 'red',
 'blue',
 'red',
 'red',
 'red',
 'blue',
 'red',
 'green',
 'green',
 'blue',
 'red',
 'red',
 'blue',
 'red',
 'blue',
 'blue',
 'red',
 'red',
 'blue',
 'red',
 'green',
 'red',
 'blue',
 'red',
 'blue',
 'red',
 'green',
 'blue',
 'green',
 'red',
 'blue',
 'red',
 'blue',
 'red',
 'red',
 'blue',
 'green',
 'blue',
 'blue',
 'blue',
 'blue',
 'red',
 'blue',
 'red',
 'blue',
 'red',
 'red',
 'red',
 'red',
 'red',
 'red',
 'red',
 'green',
 'red',
 'red',
 'blue',
 'red',
 'red',
 'red',
 'green',
 'red',
 'blu

In [39]:
viewer.add_points(dots, size = 20, face_color=color_array)

<Points layer 'dots [2]' at 0x7ff73bbd3d50>

In [7]:
help(viewer.add_points)

Help on method add_points:

add_points(data=None, *, ndim=None, features=None, properties=None, text=None, symbol='o', size=10, edge_width=1, edge_color='black', edge_color_cycle=None, edge_colormap='viridis', edge_contrast_limits=None, face_color='white', face_color_cycle=None, face_colormap='viridis', face_contrast_limits=None, out_of_slice_display=False, n_dimensional=None, name=None, metadata=None, scale=None, translate=None, rotate=None, shear=None, affine=None, opacity=1, blending='translucent', visible=True, cache=True, property_choices=None, experimental_clipping_planes=None, shading='none', experimental_canvas_size_limits=(0, 10000), shown=True) -> napari.layers.points.points.Points method of napari.viewer.Viewer instance
    Add a Points layer to the layer list. 
    
    Parameters
    ----------
    data : array (N, D)
        Coordinates for N points in D dimensions.
    ndim : int
        Number of dimensions for shapes. When data is not None, ndim must be D.
        An e

In [ ]:
napari.add_points

In [19]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

In [23]:
def rep(data_series):
    return np.reshape(np.array(data_series), (len(data_series), 1))

In [31]:
np.concatenate((rep(df.x), rep(df.y)), axis=1)

array([[10018.54545455, 10127.09090909],
       [10059.47826087, 10066.52173913],
       [10103.75      , 10022.83333333],
       ...,
       [11696.125     , 12307.375     ],
       [11018.        , 14830.        ],
       [13513.66666667, 12328.        ]])

In [ ]:
np.concatenate(df.x)

In [14]:
with open(DATA, 'r') as fh:
    data = json.load(fh)

In [15]:
data

{'geometries': [{'coordinates': [[[1121.0, 241.0],
     [1119.0, 232.0],
     [1116.0, 211.0],
     [1095.0, 187.0],
     [1060.0, 213.0],
     [1053.0, 212.0],
     [1030.0, 226.0],
     [1047.0, 259.0],
     [1052.0, 274.0],
     [1051.0, 287.0],
     [1067.0, 281.0],
     [1089.0, 290.0],
     [1099.0, 258.0],
     [1121.0, 241.0]]],
   'type': 'Polygon',
   'cell': 56},
  {'coordinates': [[[903.0, 226.0],
     [914.0, 247.0],
     [934.0, 249.0],
     [952.0, 245.0],
     [981.0, 250.0],
     [982.0, 221.0],
     [967.0, 200.0],
     [994.0, 174.0],
     [945.0, 169.0],
     [927.0, 173.0],
     [931.0, 185.0],
     [910.0, 217.0],
     [903.0, 226.0]]],
   'type': 'Polygon',
   'cell': 35},
  {'coordinates': [[[1138.0, 804.0],
     [1123.0, 798.0],
     [1127.0, 792.0],
     [1120.0, 795.0],
     [1107.0, 800.0],
     [1104.0, 814.0],
     [1093.0, 825.0],
     [1077.0, 841.0],
     [1070.0, 868.0],
     [1089.0, 883.0],
     [1082.0, 890.0],
     [1094.0, 890.0],
     [1130.0, 87

In [28]:
data['geometries'][0]

{'coordinates': [[[17821.0, 36211.0],
   [17835.0, 36224.0],
   [17848.0, 36221.0],
   [17849.0, 36216.0],
   [17844.0, 36205.0],
   [17844.0, 36194.0],
   [17850.0, 36192.0],
   [17855.0, 36192.0],
   [17859.0, 36186.0],
   [17856.0, 36183.0],
   [17834.0, 36191.0],
   [17811.0, 36191.0],
   [17821.0, 36211.0]]],
 'type': 'Polygon',
 'cell': 29965}

In [30]:
data['geometries'][1]

{'coordinates': [[[28639.0, 11545.0],
   [28627.0, 11535.0],
   [28622.0, 11525.0],
   [28609.0, 11535.0],
   [28606.0, 11543.0],
   [28626.0, 11554.0],
   [28639.0, 11545.0]]],
 'type': 'Polygon',
 'cell': 45120}

In [32]:
data['geometries'][0]['coordinates'][0]

[[17821.0, 36211.0],
 [17835.0, 36224.0],
 [17848.0, 36221.0],
 [17849.0, 36216.0],
 [17844.0, 36205.0],
 [17844.0, 36194.0],
 [17850.0, 36192.0],
 [17855.0, 36192.0],
 [17859.0, 36186.0],
 [17856.0, 36183.0],
 [17834.0, 36191.0],
 [17811.0, 36191.0],
 [17821.0, 36211.0]]

In [28]:
cells = []
for i, cell in enumerate(data['geometries'][:]):
    #if i == 1:
    #    print(np.array(cell['coordinates'][0]).shape)
    polygon_array = np.array(cell['coordinates'][0])
    cells.append(np.flip(polygon_array, axis=1))

In [29]:
polygon_array

array([[423., 222.],
       [444., 252.],
       [445., 263.],
       [439., 287.],
       [446., 286.],
       [470., 307.],
       [478., 315.],
       [490., 295.],
       [477., 250.],
       [449., 217.],
       [430., 222.],
       [423., 222.]])

In [30]:
cells[-1]

array([[222., 423.],
       [252., 444.],
       [263., 445.],
       [287., 439.],
       [286., 446.],
       [307., 470.],
       [315., 478.],
       [295., 490.],
       [250., 477.],
       [217., 449.],
       [222., 430.],
       [222., 423.]])

In [17]:
len(cells)

202

In [18]:
cells

[array([[1121.,  241.],
        [1119.,  232.],
        [1116.,  211.],
        [1095.,  187.],
        [1060.,  213.],
        [1053.,  212.],
        [1030.,  226.],
        [1047.,  259.],
        [1052.,  274.],
        [1051.,  287.],
        [1067.,  281.],
        [1089.,  290.],
        [1099.,  258.],
        [1121.,  241.]]),
 array([[903., 226.],
        [914., 247.],
        [934., 249.],
        [952., 245.],
        [981., 250.],
        [982., 221.],
        [967., 200.],
        [994., 174.],
        [945., 169.],
        [927., 173.],
        [931., 185.],
        [910., 217.],
        [903., 226.]]),
 array([[1138.,  804.],
        [1123.,  798.],
        [1127.,  792.],
        [1120.,  795.],
        [1107.,  800.],
        [1104.,  814.],
        [1093.,  825.],
        [1077.,  841.],
        [1070.,  868.],
        [1089.,  883.],
        [1082.,  890.],
        [1094.,  890.],
        [1130.,  878.],
        [1121.,  868.],
        [1135.,  846.],
        [1148.

In [10]:
np.min(cells[1][:, 0])

28606.0

In [11]:
def fov_region(cells: list, xmin, xmax, ymin, ymax):
    #x_tuple = (xmin, )
    fov_cells = []
    for cell in cells:
        cell_xmin, cell_xmax = np.min(cell[:, 0]), np.max(cell[:, 0])
        cell_ymin, cell_ymax = np.min(cell[:, 1]), np.max(cell[:, 1])
        if (cell_xmin > xmin) & (cell_xmax < xmax):
            fov_cells.append(cell)
    return fov_cells

In [21]:
viewer.add_shapes(cells, shape_type='polygon')

<Shapes layer 'cells' at 0x7fd368b53280>

In [25]:
cells[0].shape

(14, 2)

In [24]:
rep(cells[0])

ValueError: cannot reshape array of size 28 into shape (14,1)

In [ ]:
np.reshape(np.array(cells[0]), (len(cells[0]), 2))